version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 32282:1972
      - 32283:52773
      - 32284:53773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./:/irisdev/app

  irisfhir:
    build: 
      context: irisfhir
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972
      - 8083:52773
      - 53773
    volumes:
      - ~/iris.key:/usr/irissys/mgr/iris.key
      - ./irisfhir:/irisdev/app/

  hapifhirorganization:
    image: hapiproject/hapi:v5.3.0
    ports:
      - "8082:8080"
    environment:
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://postgresdborganization:5432/hapifhir'
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      # - "tester.server_address=http://localhost:8080/fhir"
    depends_on:
      - postgresdborganization

  postgresdborganization:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapifhir
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5432"

  hapifhirclaim:
    image: hapiproject/hapi:v5.3.0
    ports:
      - "8081:8080"
    environment:
      profiles.active: r4
      spring.datasource.url: 'jdbc:postgresql://postgresdbclaim:5432/hapifhir'
      spring.datasource.username: admin
      spring.datasource.password: admin
      spring.datasource.driverClassName: org.postgresql.Driver
      hapi.fhir.allow_external_references: true
      # - "tester.server_address=http://localhost:8080/fhir"
    depends_on:
      - postgresdbclaim

  postgresdbclaim:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapifhir
    # not needed for networking between containers but here for troubleshooting
    ports:
      - "5432"