---
services:
  alertmanager:
    command:
      - --config.file=/config/isc_alertmanager.yml
      - --data.retention=24h
      - --cluster.listen-address=
    depends_on:
      - sam
      - prometheus
    expose:
      - '9093'
    build:
      context: ./config/alertmanager
      dockerfile: Dockerfile
    restart: on-failure
  grafana:
    depends_on:
      - prometheus
    expose:
      - '3000'
    build: 
      context: ./config/grafana
      dockerfile: Dockerfile
    restart: on-failure
  sam:
    command: 
      - '--check-caps false'
      - -a 
      - iris session iris -U%SYS '##class(Security.Users).UnExpireUserPasswords("*")'
    expose:
      - '51773'
      - '52773'
    image: containers.intersystems.com/intersystems/sam:2.0.1.181
    init: true
    restart: on-failure
    volumes:
      - ./config:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  nginx:
    depends_on:
      - sam
      - prometheus
      - grafana
    image: nginx:1.23.1-alpine
    ports:
      - 8088:8080
    restart: on-failure
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
  prometheus:
    command:
      - --web.enable-lifecycle
      - --config.file=/config/isc_prometheus.yml
      - --storage.tsdb.retention.time=2h
    depends_on:
      - sam
    expose:
      - '9090'
    build:
      context: ./config/prometheus
      dockerfile: Dockerfile
    restart: on-failure
version: '3.7'

networks:
  default:
    external:
      name: iris-fhir-multi-server_default
