{
 "title": "SAM Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "label": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "HL7 In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iris_interop_messages_per_sec{instance=\"[[Instance]]\",host=\"HL7_Default_TCP_Service\"}",
     "legendFormat": "HL7 TCP in"
    },
    {
     "expr": "iris_interop_messages_per_sec{instance=\"[[Instance]]\",host=\"HL7_Default_File_Service\"}",
     "legendFormat": "HL7 File in"
    }
   ]
  },
  {
   "title": "Database Reads",
   "type": "graph",
   "description": "## Physical Reads\n\nThe number of database blocks (8K and other sizes [if any]) read from disk per second. \n\nThis is the Disk I/O read activity--notice that on active systems there is always non-zero read data.\n",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "iris_phys_reads_per_sec{job=\"SAM\", instance=\"[[Instance]]\"}",
     "legendFormat": "Database Reads"
    }
   ]
  },
  {
   "title": "IRIS Database Latency",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "iris_db_latency{id=\"IRISSYS\", job=\"SAM\", instance=\"[[Instance]]\"}",
     "legendFormat": "Database Latency"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "iris_cpu_usage{job=\"SAM\", instance=\"[[Instance]]\"}",
     "legendFormat": "CPU Utilization"
    }
   ]
  },
  {
   "title": "Total Pri Jnl Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 10 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "iris_jrn_size{id=\"primary\",job=\"SAM\", instance=\"[[Instance]]\"}"
    }
   ]
  },
  {
   "title": "Licence Current Pct",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "iris_license_percent_used{job=\"SAM\", instance=\"[[Instance]]\"}"
    }
   ]
  },
  {
   "title": "System Alerts",
   "type": "singlestat",
   "description": "The number of alerts posted to the messages log since system startup.",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "iris_system_alerts{job=\"SAM\", instance=\"[[Instance]]\"}"
    }
   ]
  },
  {
   "title": "Pri Jnl Free",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 12 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "iris_jrn_free_space{id=\"primary\",job=\"SAM\", instance=\"[[Instance]]\"}"
    }
   ]
  },
  {
   "title": "Licences Available",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 12 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "iris_license_available{job=\"SAM\", instance=\"[[Instance]]\"}"
    }
   ]
  },
  {
   "title": "Glorefs",
   "type": "graph",
   "description": "## Glorefs\n\nGlobal References per second is the number of times a data element was accessed whether that was from disk or from database cache. \n\nThis is a good indication of \"activity\"--high numbers mean high activity. \n\nAnother way of looking at GloRefs is as an indicator of database transaction rate.\n\n## Look for\n\n__No Hard limits__\n  \nLook for unusual deviations from baselines. \n\nLower than normal may indicate struggling with a resource - CPU, IO, or block contention, network\n\nCorrelate with disk IO\n\nHigh global references at the same time as a low database cache hit ratio (Cache Efficiency)  during peak hours will increase the physical read rate for database references.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iris_glo_ref_per_sec{job=\"SAM\", instance=\"[[Instance]]\"}",
     "legendFormat": "Glorefs"
    },
    {
     "expr": "iris_glo_ref_rem_per_sec{job=\"SAM\", instance=\"[[Instance]]\"}",
     "legendFormat": "Remote Glorefs"
    }
   ]
  },
  {
   "title": "WIJ Free",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 14 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "iris_jrn_free_space{id=\"WIJ\",job=\"SAM\", instance=\"[[Instance]]\"}"
    }
   ]
  },
  {
   "title": "Global Updates",
   "type": "graph",
   "description": "## Global updates \n\nLocal SET and KILL",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "iris_glo_update_per_sec{job=\"SAM\", instance=\"[[Instance]]\"}",
     "legendFormat": "Global Updates"
    }
   ]
  },
  {
   "title": "IRIS Disk Percent",
   "type": "bargauge",
   "description": "This shows disk percentage full for the disk that IRIS is installed on \n\n**Note:** GB remaining is much more important!",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "iris_disk_percent_full{id=\"IRISSYS\",job=\"SAM\", instance=\"[[Instance]]\"}",
     "legendFormat": "IRIS Disk Percent"
    }
   ]
  },
  {
   "title": "IRIS Disk Remaining",
   "type": "singlestat",
   "description": "MB remaining is much more important than %!",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 23 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "iris_directory_space{id=\"IRISSYS\",job=\"SAM\", instance=\"[[Instance]]\"}",
     "legendFormat": "IRIS Space Remaining"
    }
   ]
  }
 ]
}